title: Love for Love
author: R&S
email: 1954099959@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Love is everywhere yet nowhere.
  R&S❤

# social links
github_username:  R&S # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme:minima
